### ISSUE TITLE
What about logout???

### ISSUE THREAD

**Issue by nishanth123kgr** [Dirk-Sandberg/FirebaseLoginScreen#5]
Hey Erik give some information about logging out

**Comment by GawronDev** [comment]
Clear refresh token, and change the firebase_login_screen.login_sucess variable to `False`. Thats how I did it and it works!
This is the code from my MDApp class:


   def logout(self):
        print(self.path_to_refresh_token)
        f = open(self.path_to_refresh_token, "r+")
        f.truncate(0)
        f.close()

        self.root.ids.firebase_login_screen.refresh_token = ""
        self.root.ids.firebase_login_screen.login_success = False

**Comment by Dirk-Sandberg** [comment]
Thanks for bringing this up @nishanth123kgr and @GawronDev. I just pushed a big update to this project and included a log out feature. Here's an example of how to use it. It basically does the same thing as @GawronDev's solution: https://github.com/Dirk-Sandberg/FirebaseLoginScreen/blob/a17a9b66ef2f5dac34087bb9fbb179bbcaeadec7/examples/main.py#L11
