### ISSUE TITLE
Unable to import package inside kv file

### ISSUE THREAD

**Issue by Gink3** [Dirk-Sandberg/FirebaseLoginScreen#7]
I get this error message. I have tried with both using pip install and manually cloning the git repo

```
      1:#:include FireBaseLoginScreen/firebaseloginscreen/firebaseloginscreen.kv
 >>    2:#:import FireBaseLoginScreen FireBaseLoginScreen.firebaseloginscreen.FireBaseLoginScreen
       3:
       4:ScreenManager:
 ...
 Unable to import package 'FireBaseLoginScreen.firebaseloginscreen.FireBaseLoginScreen'
```

**Comment by Maxen789** [comment]
Have you fixed this issue yet?

**Comment by sujal-suhaas** [comment]
I found the answer you need to install firebaseloginscreen by using pip in cmd or terminal if you have installed it in pycharm it will not work you need to manually install it again to install it type.
`pip install firebaseloginscreen`

**Comment by saiffayed** [comment]
I'm having the same issue, I have installed it using cmd prompt and as well as in my IDE terminal and still getting this error message

**Comment by fsvnh** [comment]
was anyone able to find a solution?

**Comment by saiffayed** [comment]
> was anyone able to find a solution?

Only worked on Mac/Linux for me

**Comment by fsvnh** [comment]
> > was anyone able to find a solution?
> 
> Only worked on Mac/Linux for me

I am also on a Mac/Linux. Did you have to do anything specific? I have tried the following:
1. toolchain pip3 install firebaseloginscreen in the kivy-ios directory
2. pip3 install firebaseloginscreen

**Comment by saiffayed** [comment]
> > > was anyone able to find a solution?
> > 
> > 
> > Only worked on Mac/Linux for me
> 
> I am also on a Mac/Linux. Did you have to do anything specific? I have tried the following:
> 
> 1. toolchain pip3 install firebaseloginscreen in the kivy-ios directory
> 2. pip3 install firebaseloginscreen

There may be a couple more installs, or install in proper directory

**Comment by fsvnh** [comment]
> > > > was anyone able to find a solution?
> > > 
> > > 
> > > Only worked on Mac/Linux for me
> > 
> > 
> > I am also on a Mac/Linux. Did you have to do anything specific? I have tried the following:
> > 
> > 1. toolchain pip3 install firebaseloginscreen in the kivy-ios directory
> > 2. pip3 install firebaseloginscreen
> 
> There may be a couple more installs, or install in proper directory

I am very new to programming. Can you explain to me how I can check whether I have multiple installations or if its the proper directory? I am not sure how to determine if using the toolchain was used correctly. I did do pip3 freeze and found that I have the 1.0.10version installed.
